/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => InsertSymbolPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");

// symbols.ts
var SYMBOL_CATEGORIES = {
  "Arrows": [
    { "name": "Left Arrow", "symbol": "\u2190" },
    { "name": "Up Arrow", "symbol": "\u2191" },
    { "name": "Right Arrow", "symbol": "\u2192" },
    { "name": "Down Arrow", "symbol": "\u2193" },
    { "name": "Left Right Arrow", "symbol": "\u2194" },
    { "name": "Up Down Arrow", "symbol": "\u2195" },
    { "name": "North West Arrow", "symbol": "\u2196" },
    { "name": "North East Arrow", "symbol": "\u2197" },
    { "name": "South East Arrow", "symbol": "\u2198" },
    { "name": "South West Arrow", "symbol": "\u2199" },
    { "name": "Leftwards Arrow with Stroke", "symbol": "\u219A" },
    { "name": "Rightwards Arrow with Stroke", "symbol": "\u219B" },
    { "name": "Leftwards Paired Arrows", "symbol": "\u21C7" },
    { "name": "Upwards Paired Arrows", "symbol": "\u21C8" },
    { "name": "Rightwards Paired Arrows", "symbol": "\u21C9" },
    { "name": "Downwards Paired Arrows", "symbol": "\u21CA" },
    { "name": "Leftwards Harpoon with Barb Upwards", "symbol": "\u21BC" },
    { "name": "Rightwards Harpoon with Barb Upwards", "symbol": "\u21C0" },
    { "name": "Leftwards Harpoon with Barb Downwards", "symbol": "\u21BD" },
    { "name": "Rightwards Harpoon with Barb Downwards", "symbol": "\u21C1" },
    { "name": "Rightwards Arrow with Corner Downwards", "symbol": "\u21B3" },
    { "name": "Downwards Arrow with Corner Leftwards", "symbol": "\u21B2" },
    { "name": "Anticlockwise Top Semicircle Arrow", "symbol": "\u21B6" },
    { "name": "Clockwise Top Semicircle Arrow", "symbol": "\u21B7" },
    { "name": "Arrow Pointing Rightwards Then Curving Upwards", "symbol": "\u2934" },
    { "name": "Arrow Pointing Rightwards Then Curving Downwards", "symbol": "\u2935" },
    { "name": "Right Double Arrow", "symbol": "\u21D2" },
    { "name": "Left Double Arrow", "symbol": "\u21D0" },
    { "name": "Up Double Arrow", "symbol": "\u21E7" },
    { "name": "Down Double Arrow", "symbol": "\u21E9" },
    { "name": "Long Right Arrow", "symbol": "\u27F6" },
    { "name": "Long Left Arrow", "symbol": "\u27F5" },
    { "name": "Long Left Right Arrow", "symbol": "\u27F7" },
    { "name": "Right Triangle Arrowhead", "symbol": "\u25B6" },
    { "name": "Left Triangle Arrowhead", "symbol": "\u25C0" },
    { "name": "Up Triangle Arrowhead", "symbol": "\u25B2" },
    { "name": "Down Triangle Arrowhead", "symbol": "\u25BC" },
    { "name": "Equivalent Arrow", "symbol": "\u21D4" },
    { "name": "Long Implies Arrow", "symbol": "\u27F9" },
    { "name": "Long Equivalent Arrow", "symbol": "\u27FA" }
  ],
  "Greek Letters": [
    { "name": "Alpha", "symbol": "\u03B1" },
    { "name": "Beta", "symbol": "\u03B2" },
    { "name": "Gamma", "symbol": "\u03B3" },
    { "name": "Delta", "symbol": "\u03B4" },
    { "name": "Epsilon", "symbol": "\u03B5" },
    { "name": "Zeta", "symbol": "\u03B6" },
    { "name": "Eta", "symbol": "\u03B7" },
    { "name": "Theta", "symbol": "\u03B8" },
    { "name": "Iota", "symbol": "\u03B9" },
    { "name": "Kappa", "symbol": "\u03BA" },
    { "name": "Lambda", "symbol": "\u03BB" },
    { "name": "Mu", "symbol": "\u03BC" },
    { "name": "Nu", "symbol": "\u03BD" },
    { "name": "Xi", "symbol": "\u03BE" },
    { "name": "Omicron", "symbol": "\u03BF" },
    { "name": "Pi", "symbol": "\u03C0" },
    { "name": "Rho", "symbol": "\u03C1" },
    { "name": "Sigma", "symbol": "\u03C3" },
    { "name": "Tau", "symbol": "\u03C4" },
    { "name": "Upsilon", "symbol": "\u03C5" },
    { "name": "Phi", "symbol": "\u03C6" },
    { "name": "Chi", "symbol": "\u03C7" },
    { "name": "Psi", "symbol": "\u03C8" },
    { "name": "Omega", "symbol": "\u03C9" }
  ],
  "Math Symbols": [
    { "name": "Infinity", "symbol": "\u221E" },
    { "name": "Pi", "symbol": "\u03C0" },
    { "name": "Sum", "symbol": "\u2211" },
    { "name": "Integral", "symbol": "\u222B" },
    { "name": "Not Equal", "symbol": "\u2260" },
    { "name": "Greater Than or Equal To", "symbol": "\u2265" },
    { "name": "Less Than or Equal To", "symbol": "\u2264" },
    { "name": "Plus-Minus", "symbol": "\xB1" },
    { "name": "Multiplication", "symbol": "\xD7" },
    { "name": "Division", "symbol": "\xF7" },
    { "name": "Square Root", "symbol": "\u221A" },
    { "name": "Proportional To", "symbol": "\u221D" },
    { "name": "Almost Equal To", "symbol": "\u2248" },
    { "name": "Angle", "symbol": "\u2220" },
    { "name": "Perpendicular", "symbol": "\u22A5" },
    { "name": "Parallel", "symbol": "\u2225" },
    { "name": "Logical And", "symbol": "\u2227" },
    { "name": "Logical Or", "symbol": "\u2228" },
    { "name": "Intersection", "symbol": "\u2229" },
    { "name": "Union", "symbol": "\u222A" },
    { "name": "Element Of", "symbol": "\u2208" },
    { "name": "Not an Element Of", "symbol": "\u2209" },
    { "name": "Subset Of", "symbol": "\u2282" },
    { "name": "Superset Of", "symbol": "\u2283" },
    { "name": "Empty Set", "symbol": "\u2205" },
    { "name": "For All", "symbol": "\u2200" },
    { "name": "There Exists", "symbol": "\u2203" },
    { "name": "Therefore", "symbol": "\u2234" },
    { "name": "Because", "symbol": "\u2235" }
  ]
};

// main.ts
var InsertSymbolPlugin = class extends import_obsidian.Plugin {
  async onload() {
    this.addCommand({
      id: "insert-symbol",
      name: "Insert Symbol",
      editorCallback: (editor, view) => {
        this.showCategoryMenu(editor, view);
      }
    });
  }
  showCategoryMenu(editor, view) {
    const menu = new import_obsidian.Menu();
    for (const category in SYMBOL_CATEGORIES) {
      menu.addItem((item) => {
        item.setTitle(category).onClick(() => {
          this.showSymbolMenu(category, editor, view);
        });
      });
    }
    const leaf = view.leaf;
    const editorView = leaf.view.editor.cm;
    const coords = editorView.coordsAtPos(editorView.state.selection.main.head);
    menu.showAtPosition({ x: coords.left, y: coords.top + 20 });
  }
  showSymbolMenu(category, editor, view) {
    const menu = new import_obsidian.Menu();
    const symbols = SYMBOL_CATEGORIES[category];
    symbols.forEach((symbol) => {
      menu.addItem((item) => {
        item.setTitle(`${symbol.name} (${symbol.symbol})`).onClick(() => {
          editor.replaceSelection(symbol.symbol);
        });
      });
    });
    const leaf = view.leaf;
    const editorView = leaf.view.editor.cm;
    const coords = editorView.coordsAtPos(editorView.state.selection.main.head);
    menu.showAtPosition({ x: coords.left, y: coords.top + 20 });
  }
};
