
export const SYMBOL_CATEGORIES = {
    "Arrows": [
        { "name": "Left Arrow", "symbol": "←" },
        { "name": "Up Arrow", "symbol": "↑" },
        { "name": "Right Arrow", "symbol": "→" },
        { "name": "Down Arrow", "symbol": "↓" },
        { "name": "Left Right Arrow", "symbol": "↔" },
        { "name": "Up Down Arrow", "symbol": "↕" },
        { "name": "North West Arrow", "symbol": "↖" },
        { "name": "North East Arrow", "symbol": "↗" },
        { "name": "South East Arrow", "symbol": "↘" },
        { "name": "South West Arrow", "symbol": "↙" },
        { "name": "Leftwards Arrow with Stroke", "symbol": "↚" },
        { "name": "Rightwards Arrow with Stroke", "symbol": "↛" },
        { "name": "Leftwards Paired Arrows", "symbol": "⇇" },
        { "name": "Upwards Paired Arrows", "symbol": "⇈" },
        { "name": "Rightwards Paired Arrows", "symbol": "⇉" },
        { "name": "Downwards Paired Arrows", "symbol": "⇊" },
        { "name": "Leftwards Harpoon with Barb Upwards", "symbol": "↼" },
        { "name": "Rightwards Harpoon with Barb Upwards", "symbol": "⇀" },
        { "name": "Leftwards Harpoon with Barb Downwards", "symbol": "↽" },
        { "name": "Rightwards Harpoon with Barb Downwards", "symbol": "⇁" },
        { "name": "Rightwards Arrow with Corner Downwards", "symbol": "↳" },
        { "name": "Downwards Arrow with Corner Leftwards", "symbol": "↲" },
        { "name": "Anticlockwise Top Semicircle Arrow", "symbol": "↶" },
        { "name": "Clockwise Top Semicircle Arrow", "symbol": "↷" },
        { "name": "Arrow Pointing Rightwards Then Curving Upwards", "symbol": "⤴" },
        { "name": "Arrow Pointing Rightwards Then Curving Downwards", "symbol": "⤵" },
        { "name": "Right Double Arrow", "symbol": "⇒" },
        { "name": "Left Double Arrow", "symbol": "⇐" },
        { "name": "Up Double Arrow", "symbol": "⇧" },
        { "name": "Down Double Arrow", "symbol": "⇩" },
        { "name": "Long Right Arrow", "symbol": "⟶" },
        { "name": "Long Left Arrow", "symbol": "⟵" },
        { "name": "Long Left Right Arrow", "symbol": "⟷" },
        { "name": "Right Triangle Arrowhead", "symbol": "▶" },
        { "name": "Left Triangle Arrowhead", "symbol": "◀" },
        { "name": "Up Triangle Arrowhead", "symbol": "▲" },
        { "name": "Down Triangle Arrowhead", "symbol": "▼" },
        { "name": "Equivalent Arrow", "symbol": "⇔" },
        { "name": "Long Implies Arrow", "symbol": "⟹" },
        { "name": "Long Equivalent Arrow", "symbol": "⟺" }
    ],
    "Greek Letters": [
        { "name": "Alpha", "symbol": "α" },
        { "name": "Beta", "symbol": "β" },
        { "name": "Gamma", "symbol": "γ" },
        { "name": "Delta", "symbol": "δ" },
        { "name": "Epsilon", "symbol": "ε" },
        { "name": "Zeta", "symbol": "ζ" },
        { "name": "Eta", "symbol": "η" },
        { "name": "Theta", "symbol": "θ" },
        { "name": "Iota", "symbol": "ι" },
        { "name": "Kappa", "symbol": "κ" },
        { "name": "Lambda", "symbol": "λ" },
        { "name": "Mu", "symbol": "μ" },
        { "name": "Nu", "symbol": "ν" },
        { "name": "Xi", "symbol": "ξ" },
        { "name": "Omicron", "symbol": "ο" },
        { "name": "Pi", "symbol": "π" },
        { "name": "Rho", "symbol": "ρ" },
        { "name": "Sigma", "symbol": "σ" },
        { "name": "Tau", "symbol": "τ" },
        { "name": "Upsilon", "symbol": "υ" },
        { "name": "Phi", "symbol": "φ" },
        { "name": "Chi", "symbol": "χ" },
        { "name": "Psi", "symbol": "ψ" },
        { "name": "Omega", "symbol": "ω" }
    ],
    "Math Symbols": [
        { "name": "Infinity", "symbol": "∞" },
        { "name": "Pi", "symbol": "π" },
        { "name": "Sum", "symbol": "∑" },
        { "name": "Integral", "symbol": "∫" },
        { "name": "Not Equal", "symbol": "≠" },
        { "name": "Greater Than or Equal To", "symbol": "≥" },
        { "name": "Less Than or Equal To", "symbol": "≤" },
        { "name": "Plus-Minus", "symbol": "±" },
        { "name": "Multiplication", "symbol": "×" },
        { "name": "Division", "symbol": "÷" },
        { "name": "Square Root", "symbol": "√" },
        { "name": "Proportional To", "symbol": "∝" },
        { "name": "Almost Equal To", "symbol": "≈" },
        { "name": "Angle", "symbol": "∠" },
        { "name": "Perpendicular", "symbol": "⊥" },
        { "name": "Parallel", "symbol": "∥" },
        { "name": "Logical And", "symbol": "∧" },
        { "name": "Logical Or", "symbol": "∨" },
        { "name": "Intersection", "symbol": "∩" },
        { "name": "Union", "symbol": "∪" },
        { "name": "Element Of", "symbol": "∈" },
        { "name": "Not an Element Of", "symbol": "∉" },
        { "name": "Subset Of", "symbol": "⊂" },
        { "name": "Superset Of", "symbol": "⊃" },
        { "name": "Empty Set", "symbol": "∅" },
        { "name": "For All", "symbol": "∀" },
        { "name": "There Exists", "symbol": "∃" },
        { "name": "Therefore", "symbol": "∴" },
        { "name": "Because", "symbol": "∵" }
    ]
};
